### ISSUE TITLE
Fixing duration text for videos

### ISSUE THREAD

**Issue by kubestaff** [kubestaff/golearn#35]
The duration info in the list of videos is wrong when a video has a duration like 90 seconds it's displayed as 1 minute where it should be 1 minute and 30 seconds

**Comment by IgorM1996** [comment]
Can I book a session please? For tomorrow?

Igor,
________________________________

**Comment by kubestaff** [comment]
sure plz contact me over chat

**Comment by IgorM1996** [comment]
My apologies, but I don't have the chat due to extenuating circumstances. Once everything is sorted I will be on it.

________________________________
